### PR TITLE
DB-compatibility for TYPO3 8.x.

### PR DESCRIPTION
**Pull request by mkalus**
Our agency (eberl-online.de) created changes to make extension compatible for TYPO3 8.x. - we would be happy if this would be incorporated into main line.

### CODE REVIEW

**Comment by tobikummer** [comment]
Same here, would be great to use it in TYPO3 8 LTS!

**Comment by mkalus** [comment]
What we did not do, I realize now, is to have downward-compatibility in the CR. Would be relatively simple to achieve, I guess.

**Comment by spoonerWeb** [comment]
Why is there a need to change to Doctrine? 
Imho the old exec_SELECTquery is still working in v8.
As you said, it will break the extension for v7 and before.

**Comment by spoonerWeb** [comment]
@mkalus Is it not working with v8 without these changes?

**Comment by tobikummer** [comment]
This extension won't work in TYPO3 8 LTS. 
`'php' => '5.3.0-5.6.99',
'typo3' => '6.2.0-7.99.99',`
At least, this two dependencies makes an installation impossible.
Create a version 8 with "mklaus" changes and correct dependencies. So the backwards compatibility is no problem with the correct version/tag...

**Comment by spoonerWeb** [comment]
There is a new version with support for 8 LTS. Please test this and add issues if there are problems.
I will close this PR due too breaking changes which are not needed for 8 LTS support

**Pull request closed without merging**
